[build]
  command = "chmod +x build-helper.sh && ./build-helper.sh && npm run build && chmod +x post-build.sh && ./post-build.sh"
  publish = ".next"

[build.environment]
  NEXT_PRIVATE_TARGET = "server"
  NODE_VERSION = "20.11.1"  # Updated to Node.js 20 for Next.js compatibility
  # Enable streaming responses in Next.js
  NEXT_PRIVATE_PREBUNDLED_REACT = "1"
  # Include placeholder Supabase values for build time
  NEXT_PUBLIC_SUPABASE_URL = "https://placeholder-during-build.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "placeholder-key-during-build"
  SUPABASE_SERVICE_ROLE_KEY = "placeholder-role-key-during-build"
  # Flag to indicate we're in Netlify build environment
  NETLIFY = "true"
  # Add Next.js 13+ specific settings
  NEXT_USE_NETLIFY_EDGE = "true"

# Use the official Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# The order of redirects is important!
# First, handle static and image assets
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/_next/image*"
  to = "/_next/image:splat"
  status = 200
  force = true

[[redirects]]
  from = "/_next/data/*"
  to = "/_next/data/:splat"
  status = 200
  force = true

# Handle public assets
[[redirects]]
  from = "/public/*"
  to = "/:splat"
  status = 200

# Special redirect for favicon and other root files
[[redirects]]
  from = "/favicon.ico"
  to = "/favicon.ico"
  status = 200

# Then, handle dynamic routes through Next.js functions
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs"
  status = 200

[functions]
  # Set a higher timeout for Next.js functions
  node_bundler = "esbuild"
  external_node_modules = ["better-sqlite3"]
  included_files = ["!node_modules/.pnpm/better-sqlite3*/node_modules/better-sqlite3/build/Release/better_sqlite3.node"]
  
# Cache control for static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"